import pandas as pd
import numpy as np
import os
from scipy.stats import kurtosis, skew

# =====================
# CONFIG
# =====================
DATA_PATH = "data/all_simulations.csv"
OUTPUT_PATH = "data/window_features.csv"

WINDOW_SIZE = 50 
STRIDE = 10 

# =====================
# LOAD DATA
# =====================
if not os.path.exists(DATA_PATH):
    print(f"Error: {DATA_PATH} not found. Run batch_generate.py first.")
    exit()

df = pd.read_csv(DATA_PATH)
feature_rows = []

print("Processing windows with Kalman Innovation features...")

# =====================
# PROCESS PER RUN
# =====================
for run_id, run_df in df.groupby("run_id"):
    run_df = run_df.sort_values("time").reset_index(drop=True)
    scenario = run_df["scenario_id"].iloc[0]

    for start in range(0, len(run_df) - WINDOW_SIZE, STRIDE):
        window = run_df.iloc[start:start + WINDOW_SIZE]

        # 1. Feature Signals
        # -----------------------------------------------
        # We now use the 'innovation' column generated by the Kalman Filter
        # This is the "Physics-Aware" error signal.
        innov = window["innovation"].fillna(0)
        
        # We still use the raw residual for comparison
        sensor_val = window["omega_sensor"].ffill().fillna(0)
        residual = np.abs(window["omega_true"] - sensor_val)

        # 2. Hybrid Feature Extraction (Model-Based + Statistical)
        # -----------------------------------------------
        rms_innov = np.sqrt(np.mean(innov**2))
        peak_innov = np.max(np.abs(innov))
        
        features = {
            # Standard Residual Features
            "res_mean": residual.mean(),
            "res_std": residual.std(),
            
            # Kalman Innovation Features (Highly sensitive to cyber-attacks)
            "innov_mean": innov.mean(),
            "innov_std": innov.std(),
            "innov_max": peak_innov,
            
            # Advanced Statistical Features on Innovation
            "innov_kurtosis": kurtosis(innov),
            "innov_skew": skew(innov),
            "innov_crest": peak_innov / rms_innov if rms_innov != 0 else 0,
            
            # Physics-based Trend
            "res_slope": np.polyfit(range(len(residual)), residual, 1)[0],
            "omega_kalman_mean": window["omega_kalman"].mean()
        }

        # 3. Multiclass Labeling Logic
        # ----------------------------
        attack_in_window = window["attack_active"].max() == 1
        fault_in_window = window["fault_active"].max() == 1

        if attack_in_window:
            if scenario == 2: label = 2   
            elif scenario == 3: label = 3 
            elif scenario == 4: label = 4 
            else: label = 2               
        elif fault_in_window:
            label = 1                     
        else:
            label = 0                     

        # 4. RUL and Metadata
        # ---------------------------
        features["label"] = label
        features["RUL"] = window["RUL"].iloc[-1]
        features["run_id"] = run_id
        
        feature_rows.append(features)

# =====================
# SAVE OUTPUT
# =====================
features_df = pd.DataFrame(feature_rows)
features_df.to_csv(OUTPUT_PATH, index=False)

print(f"\nProcessing Complete!")
print(f"Total Features Extracted: {len(features_df.columns) - 3}")
print("Label Distribution:")
print(features_df["label"].value_counts().sort_index())