import pandas as pd
import numpy as np
from utils.config import WINDOW_SIZE, STRIDE, DATA_PATH
from scipy.stats import kurtosis

def extract_features(df):
    rows = []

    # Constants for physics-check features
    Ke = 0.1
    R = 2.0

    for start in range(0, len(df) - WINDOW_SIZE, STRIDE):
        window = df.iloc[start:start + WINDOW_SIZE]

        # 1. SPEED RESIDUAL (Hacker detection)
        # In deployment, replace omega_true with omega_kalman
        res_speed = np.abs(window["omega_true"] - window["omega_sensor"])

        # 2. PHYSICS VIOLATION FEATURE (The "Fusion" part)
        # Ohm's Law Check: V = IR + Ke*omega => Expected Current = (V - Ke*w)/R
        # If this doesn't match window["current_sensor"], something is being spoofed.
        expected_current = (12.0 - Ke * window["omega_sensor"]) / R
        fusion_residual = np.abs(window["current_sensor"] - expected_current)

        # 3. THERMAL DRIFT
        # Is the temperature rising faster than expected for the given current?
        temp_slope = np.polyfit(range(WINDOW_SIZE), window["temp_sensor"], 1)[0]

        features = {
            # --- Speed Features ---
            "speed_res_mean": res_speed.mean(),
            "speed_res_std": res_speed.std(),
            "speed_res_slope": np.polyfit(range(WINDOW_SIZE), res_speed, 1)[0],
            
            # --- Fusion Features (Consistency) ---
            "current_consistency_mean": fusion_residual.mean(),
            "current_consistency_std": fusion_residual.std(),
            
            # --- Thermal Features (Fault detection) ---
            "temp_mean": window["temp_sensor"].mean(),
            "temp_slope": temp_slope,
            "temp_kurtosis": kurtosis(window["temp_sensor"]),

            # --- Labels ---
            "fault": window["fault_active"].max(),
            "attack": window["attack_active"].max()
        }

        rows.append(features)

    return pd.DataFrame(rows)

if __name__ == "__main__":
    # Ensure your DATA_PATH points to the NEW multi-sensor CSV 
    # generated by the updated simulation.py
    if os.path.exists(DATA_PATH):
        df = pd.read_csv(DATA_PATH)
        features_df = extract_features(df)
        features_df.to_csv("../data/window_features_fusion.csv", index=False)
        print(f"Feature extraction complete. New feature count: {len(features_df.columns)}")
    else:
        print("Error: Multi-sensor simulation data not found.")