import shap
import pandas as pd
import xgboost as xgb
import matplotlib.pyplot as plt
from pathlib import Path
import numpy as np

# ======================================================
# CONFIGURATION
# ======================================================

BASE_DIR = Path(__file__).resolve().parent
DATA_PATH = BASE_DIR / "data" / "window_features.csv"
MODEL_PATH = BASE_DIR / "models" / "xgboost_attack_classifier.json"

# These match the actual columns in window_features.csv
# (generated by ml_pipeline/utils/feature_extractor.py)
FEATURE_NAMES = [
    "innov_mean",
    "innov_std",
    "innov_kurtosis",
    "innov_crest",
    "fusion_res_mean",
    "fusion_res_std",
    "temp_mean",
    "temp_slope",
    "res_slope",
]

CLASS_NAMES = [
    "Normal",
    "Mechanical Fault",
    "Sensor Spoofing",
    "Packet Dropout",
    "Freezing Sensor"
]

# ======================================================
# LOAD DATA
# ======================================================

print("Loading dataset...")
df = pd.read_csv(DATA_PATH)

X = df[FEATURE_NAMES]
y = df["label"]

print(f"Dataset loaded: {X.shape[0]} samples, {X.shape[1]} features")

# ======================================================
# LOAD XGBOOST MODEL
# ======================================================

print("Loading XGBoost model...")
model = xgb.XGBClassifier()
model.load_model(str(MODEL_PATH))
print("Model loaded successfully")

# ======================================================
# SHAP EXPLAINER
# ======================================================

X_sample = X.sample(200, random_state=42)

# All SHAP library explainers (TreeExplainer, KernelExplainer, shap.Explainer)
# are broken in this environment due to a SHAP/XGBoost 3.x incompatibility.
# Solution: use XGBoost's own built-in TreeSHAP (pred_contribs=True).
# This computes exact SHAP values inside XGBoost itself — no SHAP explainer needed.
print("Computing SHAP values via XGBoost native TreeSHAP...")
booster = model.get_booster()
dmatrix = xgb.DMatrix(X_sample.values, feature_names=FEATURE_NAMES)

# pred_contribs=True returns SHAP contributions including the bias term.
# Multi-class output shape: (n_samples, n_classes * (n_features + 1))
raw_contribs = booster.predict(dmatrix, pred_contribs=True)

n_classes = len(CLASS_NAMES)
n_features = len(FEATURE_NAMES)

# Reshape to (n_samples, n_classes, n_features + 1)
contribs = raw_contribs.reshape(len(X_sample), n_classes, n_features + 1)

# SHAP values per class: list of (n_samples, n_features), one per class
shap_values = [contribs[:, i, :-1] for i in range(n_classes)]
# Base values (bias term) per sample per class: (n_samples, n_classes)
base_values = contribs[:, :, -1]

print("SHAP values computed successfully")

# ======================================================
# GLOBAL SHAP SUMMARY
# ======================================================

print("Generating global SHAP summary plot...")

shap.summary_plot(
    shap_values,
    X_sample,
    feature_names=FEATURE_NAMES,
    show=False
)

plt.tight_layout()
plt.savefig("shap_global_summary.png", dpi=300)
plt.close()

print("Saved: shap_global_summary.png")

# ======================================================
# LOCAL SHAP EXPLANATION (ROBUST & FINAL)
# ======================================================

index = 0

# Predict class via booster — avoids sklearn attribute issues from JSON loading
dmatrix_single = xgb.DMatrix(X_sample.iloc[[index]].values, feature_names=FEATURE_NAMES)
probs = booster.predict(dmatrix_single)  # shape (1, n_classes)
predicted_class = int(np.argmax(probs[0]))

predicted_label = CLASS_NAMES[predicted_class]

print("\nLocal SHAP explanation")
print(f"Sample index    : {index}")
print(f"Predicted class : {predicted_class} ({predicted_label})")

# base_values[index, predicted_class] is the bias term from XGBoost's TreeSHAP
explanation = shap.Explanation(
    values=shap_values[predicted_class][index],
    base_values=base_values[index, predicted_class],
    data=X_sample.iloc[index].values,
    feature_names=FEATURE_NAMES
)

# Waterfall plot (stable replacement for force_plot)
shap.plots.waterfall(explanation, show=False)

plt.tight_layout()
plt.savefig("shap_local_explanation.png", dpi=300)
plt.close()

print("Saved: shap_local_explanation.png")

# ======================================================
# TEXT-BASED FEATURE CONTRIBUTION (FOR REPORT)
# ======================================================

print("\nTop contributing features for this prediction:")

class_shap_values = shap_values[predicted_class][index]

feature_contributions = list(
    zip(FEATURE_NAMES, class_shap_values)
)

feature_contributions.sort(key=lambda x: abs(x[1]), reverse=True)

for feat, val in feature_contributions[:5]:
    print(f"{feat:25s} : {val:+.4f}")

print("\nSHAP analysis completed successfully.")
